// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dymensionxyz/dymension/eibc/query.proto

package types

import (
	context "context"
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type FulfillmentState int32

const (
	FulfillmentState_UNDEFINED   FulfillmentState = 0
	FulfillmentState_FULFILLED   FulfillmentState = 1
	FulfillmentState_UNFULFILLED FulfillmentState = 2
)

var FulfillmentState_name = map[int32]string{
	0: "UNDEFINED",
	1: "FULFILLED",
	2: "UNFULFILLED",
}

var FulfillmentState_value = map[string]int32{
	"UNDEFINED":   0,
	"FULFILLED":   1,
	"UNFULFILLED": 2,
}

func (x FulfillmentState) String() string {
	return proto.EnumName(FulfillmentState_name, int32(x))
}

func (FulfillmentState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d85bfe71ceb5f8dc, []int{0}
}

// QueryGetDemandOrderRequest is the request type for the Query/GetDemandOrder RPC method.
type QueryGetDemandOrderRequest struct {
	// id of the demand order to get
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetDemandOrderRequest) Reset()         { *m = QueryGetDemandOrderRequest{} }
func (m *QueryGetDemandOrderRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetDemandOrderRequest) ProtoMessage()    {}
func (*QueryGetDemandOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d85bfe71ceb5f8dc, []int{2}
}
func (m *QueryGetDemandOrderRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDemandOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDemandOrderRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDemandOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDemandOrderRequest.Merge(m, src)
}
func (m *QueryGetDemandOrderRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDemandOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDemandOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDemandOrderRequest proto.InternalMessageInfo

func (m *QueryGetDemandOrderRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// QueryDemandOrdersByStatusRequest is the request type for the Query/GetDemandOrdersByStatus RPC method.
type QueryDemandOrdersByStatusRequest struct {
	// status of the demand order
	Status Status `protobuf:"varint,1,opt,name=status,proto3,enum=dymensionxyz.dymension.common.Status" json:"status,omitempty"`
	// optional type
	Type RollappPacket_Type `protobuf:"varint,2,opt,name=type,proto3,enum=dymensionxyz.dymension.common.RollappPacket_Type" json:"type,omitempty"`
	// optional rollapp_id
	RollappId string `protobuf:"bytes,3,opt,name=rollapp_id,json=rollappId,proto3" json:"rollapp_id,omitempty"`
	// optional limit
	Limit int32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	// optional fulfillment state
	FulfillmentState FulfillmentState `protobuf:"varint,5,opt,name=fulfillment_state,json=fulfillmentState,proto3,enum=dymensionxyz.dymension.eibc.FulfillmentState" json:"fulfillment_state,omitempty"`
	// optional fulfiller address
	Fulfiller string `protobuf:"bytes,6,opt,name=fulfiller,proto3" json:"fulfiller,omitempty"`
	// optional denom
	Denom string `protobuf:"bytes,7,opt,name=denom,proto3" json:"denom,omitempty"`
	// optional recipient address
	Recipient  string             `protobuf:"bytes,8,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,9,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryDemandOrdersByStatusRequest) Reset()         { *m = QueryDemandOrdersByStatusRequest{} }
func (m *QueryDemandOrdersByStatusRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDemandOrdersByStatusRequest) ProtoMessage()    {}
func (*QueryDemandOrdersByStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d85bfe71ceb5f8dc, []int{3}
}
func (m *QueryDemandOrdersByStatusRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDemandOrdersByStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDemandOrdersByStatusRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDemandOrdersByStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDemandOrdersByStatusRequest.Merge(m, src)
}
func (m *QueryDemandOrdersByStatusRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryDemandOrdersByStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDemandOrdersByStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDemandOrdersByStatusRequest proto.InternalMessageInfo

func (m *QueryDemandOrdersByStatusRequest) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_PENDING
}

func (m *QueryDemandOrdersByStatusRequest) GetType() RollappPacket_Type {
	if m != nil {
		return m.Type
	}
	return RollappPacket_ON_RECV
}

func (m *QueryDemandOrdersByStatusRequest) GetRollappId() string {
	if m != nil {
		return m.RollappId
	}
	return ""
}

func (m *QueryDemandOrdersByStatusRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *QueryDemandOrdersByStatusRequest) GetFulfillmentState() FulfillmentState {
	if m != nil {
		return m.FulfillmentState
	}
	return FulfillmentState_UNDEFINED
}

func (m *QueryDemandOrdersByStatusRequest) GetFulfiller() string {
	if m != nil {
		return m.Fulfiller
	}
	return ""
}

func (m *QueryDemandOrdersByStatusRequest) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *QueryDemandOrdersByStatusRequest) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *QueryDemandOrdersByStatusRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryGetDemandOrderResponse is the response type for the Query/GetDemandOrder RPC method.
type QueryGetDemandOrderResponse struct {
	// demand order with the given id
	DemandOrder *DemandOrder `protobuf:"bytes,1,opt,name=demand_order,json=demandOrder,proto3" json:"demand_order,omitempty"`
}

func (m *QueryGetDemandOrderResponse) Reset()         { *m = QueryGetDemandOrderResponse{} }
func (m *QueryGetDemandOrderResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetDemandOrderResponse) ProtoMessage()    {}
func (*QueryGetDemandOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d85bfe71ceb5f8dc, []int{4}
}
func (m *QueryGetDemandOrderResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDemandOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDemandOrderResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDemandOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDemandOrderResponse.Merge(m, src)
}
func (m *QueryGetDemandOrderResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDemandOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDemandOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDemandOrderResponse proto.InternalMessageInfo

func (m *QueryGetDemandOrderResponse) GetDemandOrder() *DemandOrder {
	if m != nil {
		return m.DemandOrder
	}
	return nil
}

// QueryDemandOrdersByStatusResponse is the response type for the Query/GetDemandOrdersByStatus RPC method.
type QueryDemandOrdersByStatusResponse struct {
	// A list of demand orders with the given status
	DemandOrders []*DemandOrder      `protobuf:"bytes,1,rep,name=demand_orders,json=demandOrders,proto3" json:"demand_orders,omitempty"`
	Pagination   *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryDemandOrdersByStatusResponse) Reset()         { *m = QueryDemandOrdersByStatusResponse{} }
func (m *QueryDemandOrdersByStatusResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDemandOrdersByStatusResponse) ProtoMessage()    {}
func (*QueryDemandOrdersByStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d85bfe71ceb5f8dc, []int{5}
}
func (m *QueryDemandOrdersByStatusResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDemandOrdersByStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDemandOrdersByStatusResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDemandOrdersByStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDemandOrdersByStatusResponse.Merge(m, src)
}
func (m *QueryDemandOrdersByStatusResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryDemandOrdersByStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDemandOrdersByStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDemandOrdersByStatusResponse proto.InternalMessageInfo

func (m *QueryDemandOrdersByStatusResponse) GetDemandOrders() []*DemandOrder {
	if m != nil {
		return m.DemandOrders
	}
	return nil
}

func (m *QueryDemandOrdersByStatusResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterEnum("dymensionxyz.dymension.eibc.FulfillmentState", FulfillmentState_name, FulfillmentState_value)
	proto.RegisterType((*QueryGetDemandOrderRequest)(nil), "dymensionxyz.dymension.eibc.QueryGetDemandOrderRequest")
	proto.RegisterType((*QueryDemandOrdersByStatusRequest)(nil), "dymensionxyz.dymension.eibc.QueryDemandOrdersByStatusRequest")
	proto.RegisterType((*QueryGetDemandOrderResponse)(nil), "dymensionxyz.dymension.eibc.QueryGetDemandOrderResponse")
	proto.RegisterType((*QueryDemandOrdersByStatusResponse)(nil), "dymensionxyz.dymension.eibc.QueryDemandOrdersByStatusResponse")
}

func init() {
	proto.RegisterFile("dymensionxyz/dymension/eibc/query.proto", fileDescriptor_d85bfe71ceb5f8dc)
}

var fileDescriptor_d85bfe71ceb5f8dc = []byte{
	// 877 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x41, 0x6f, 0x1b, 0x45,
	0x14, 0xf6, 0x3a, 0xb1, 0xc1, 0x2f, 0x6d, 0x12, 0x86, 0x08, 0x56, 0x6e, 0x31, 0x61, 0xab, 0x92,
	0xa8, 0x90, 0x9d, 0xc6, 0xa6, 0x80, 0x84, 0x8a, 0x14, 0x63, 0xbb, 0xb2, 0x1a, 0x42, 0xba, 0x10,
	0x84, 0x7a, 0xb1, 0xc6, 0xde, 0x89, 0x3b, 0x64, 0x77, 0x67, 0xbb, 0xbb, 0xb6, 0xba, 0x54, 0xbd,
	0xf0, 0x0b, 0x90, 0xb8, 0xf0, 0x3f, 0x38, 0xc2, 0x0f, 0xe8, 0xb1, 0xa2, 0x17, 0x4e, 0x08, 0x25,
	0x1c, 0xf9, 0x11, 0x68, 0x67, 0x66, 0xed, 0x4d, 0x13, 0xaf, 0x13, 0x6e, 0x3b, 0x6f, 0xdf, 0xf7,
	0xde, 0xf7, 0xbe, 0x79, 0xef, 0x0d, 0x6c, 0xd8, 0xb1, 0x4b, 0xbd, 0x90, 0x71, 0xef, 0x49, 0xfc,
	0x03, 0x9e, 0x1c, 0x30, 0x65, 0xfd, 0x01, 0x7e, 0x3c, 0xa2, 0x41, 0x6c, 0xfa, 0x01, 0x8f, 0x38,
	0xba, 0x96, 0x75, 0x34, 0x27, 0x07, 0x33, 0x71, 0xac, 0xae, 0x0d, 0xf9, 0x90, 0x0b, 0x3f, 0x9c,
	0x7c, 0x49, 0x48, 0xf5, 0xfa, 0x90, 0xf3, 0xa1, 0x43, 0x31, 0xf1, 0x19, 0x26, 0x9e, 0xc7, 0x23,
	0x12, 0x31, 0xee, 0x85, 0xea, 0xef, 0xad, 0x01, 0x0f, 0x5d, 0x1e, 0xe2, 0x3e, 0x09, 0xa9, 0xcc,
	0x84, 0xc7, 0xdb, 0x7d, 0x1a, 0x91, 0x6d, 0xec, 0x93, 0x21, 0xf3, 0x84, 0xb3, 0xf2, 0xdd, 0xcc,
	0x63, 0xe9, 0x93, 0x80, 0xb8, 0x69, 0x54, 0x33, 0xcf, 0xd3, 0xa6, 0x2e, 0xf1, 0xec, 0x1e, 0x0f,
	0x6c, 0x1a, 0xa4, 0x2c, 0x66, 0xf8, 0x0f, 0xb8, 0xeb, 0x72, 0x0f, 0x87, 0x11, 0x89, 0x46, 0x69,
	0xec, 0x7a, 0xbe, 0x6f, 0xc0, 0x1d, 0x87, 0xf8, 0x7e, 0xcf, 0x27, 0x83, 0x23, 0x1a, 0x29, 0xcc,
	0x56, 0x3e, 0x86, 0x79, 0x63, 0x12, 0x30, 0xe2, 0x29, 0x77, 0x63, 0x0d, 0xd0, 0x83, 0x44, 0x8a,
	0x7d, 0x51, 0x93, 0x45, 0x1f, 0x8f, 0x68, 0x18, 0x19, 0xdf, 0xc1, 0x9b, 0xa7, 0xac, 0xa1, 0xcf,
	0xbd, 0x90, 0xa2, 0x1d, 0x28, 0xcb, 0xda, 0x75, 0x6d, 0x5d, 0xdb, 0x5c, 0xaa, 0xdf, 0x30, 0x73,
	0xee, 0xc8, 0x94, 0xe0, 0xe6, 0xe2, 0xf3, 0xbf, 0xde, 0x2d, 0x58, 0x0a, 0x68, 0x7c, 0x08, 0x55,
	0x11, 0xf9, 0x1e, 0x8d, 0x5a, 0x42, 0x9c, 0xaf, 0x12, 0x6d, 0x54, 0x5e, 0xb4, 0x0c, 0x45, 0x66,
	0x8b, 0xe0, 0x15, 0xab, 0xc8, 0x6c, 0xe3, 0xe5, 0x02, 0xac, 0x0b, 0xf7, 0x8c, 0x6f, 0xd8, 0x8c,
	0xbf, 0x16, 0x22, 0xa5, 0xa0, 0xbb, 0x50, 0x96, 0xaa, 0x09, 0xe0, 0x72, 0xfd, 0xe6, 0x2c, 0x56,
	0x52, 0x02, 0x53, 0xa1, 0x15, 0x08, 0xb5, 0x61, 0x31, 0x8a, 0x7d, 0xaa, 0x17, 0x05, 0x78, 0x7b,
	0x0e, 0xd8, 0x92, 0x9a, 0xef, 0x4b, 0xc9, 0xbf, 0x89, 0x7d, 0x6a, 0x09, 0x38, 0x7a, 0x07, 0x20,
	0xbd, 0x0f, 0x66, 0xeb, 0x0b, 0xa2, 0x84, 0x8a, 0xb2, 0x74, 0x6d, 0xb4, 0x06, 0x25, 0x87, 0xb9,
	0x2c, 0xd2, 0x17, 0xd7, 0xb5, 0xcd, 0x92, 0x25, 0x0f, 0xe8, 0x21, 0xbc, 0x71, 0x38, 0x72, 0x0e,
	0x99, 0xe3, 0xb8, 0xd4, 0x8b, 0x7a, 0x09, 0x23, 0xaa, 0x97, 0x04, 0x91, 0xad, 0x5c, 0x6d, 0x3b,
	0x53, 0x54, 0x52, 0x0e, 0xb5, 0x56, 0x0f, 0x5f, 0xb1, 0xa0, 0xeb, 0x50, 0x51, 0x36, 0x1a, 0xe8,
	0x65, 0xc9, 0x67, 0x62, 0x48, 0xf8, 0xd8, 0xd4, 0xe3, 0xae, 0xfe, 0x9a, 0xf8, 0x23, 0x0f, 0x09,
	0x26, 0xa0, 0x03, 0xe6, 0x33, 0xea, 0x45, 0xfa, 0xeb, 0xaa, 0x86, 0xd4, 0x80, 0x3a, 0x00, 0xd3,
	0x41, 0xd1, 0x2b, 0xa2, 0x05, 0xde, 0x37, 0xe5, 0x54, 0x99, 0xc9, 0x54, 0x99, 0x72, 0x7e, 0xd5,
	0x54, 0x99, 0xfb, 0x64, 0x48, 0xd5, 0x25, 0x59, 0x19, 0xa4, 0xf1, 0x3d, 0x5c, 0x3b, 0xb7, 0x07,
	0x54, 0x97, 0xdd, 0x87, 0x2b, 0xd9, 0xb9, 0x51, 0xbd, 0xb6, 0x99, 0xab, 0x47, 0x36, 0xce, 0x92,
	0x3d, 0x3d, 0x18, 0xbf, 0x69, 0xf0, 0x5e, 0x4e, 0x07, 0xa9, 0x94, 0x5f, 0xc2, 0xd5, 0x6c, 0xca,
	0xa4, 0x93, 0x16, 0x2e, 0x95, 0xf3, 0x4a, 0x26, 0x67, 0x88, 0xee, 0x9d, 0x12, 0xaa, 0x28, 0xf8,
	0x6f, 0xcc, 0x15, 0x4a, 0x72, 0x39, 0xa5, 0xd4, 0x0e, 0xbc, 0x25, 0xc8, 0x77, 0xd3, 0xa9, 0x9d,
	0x34, 0xfd, 0x06, 0xac, 0x4c, 0x46, 0xb9, 0x17, 0xf0, 0x51, 0x44, 0xd5, 0xd8, 0x2c, 0x4f, 0xcc,
	0x56, 0x62, 0x35, 0x1c, 0x78, 0xfb, 0x4c, 0x08, 0x55, 0xf5, 0x03, 0x80, 0x31, 0xe3, 0x8e, 0x5c,
	0x92, 0xaa, 0xe4, 0x79, 0xfd, 0x3f, 0x09, 0xf3, 0x6d, 0x8a, 0xb4, 0x32, 0x41, 0x6e, 0xed, 0xc0,
	0xea, 0xab, 0xad, 0x89, 0xae, 0x42, 0xe5, 0x60, 0xaf, 0xd5, 0xee, 0x74, 0xf7, 0xda, 0xad, 0xd5,
	0x42, 0x72, 0xec, 0x1c, 0xec, 0x76, 0xba, 0xbb, 0xbb, 0xed, 0xd6, 0xaa, 0x86, 0x56, 0x60, 0xe9,
	0x60, 0x6f, 0x6a, 0x28, 0xd6, 0xff, 0x2d, 0x41, 0x49, 0x30, 0x46, 0xbf, 0x68, 0x50, 0x96, 0x4b,
	0x04, 0xe1, 0xdc, 0x9b, 0x38, 0xbb, 0xc1, 0xaa, 0xb7, 0x2f, 0x0e, 0x90, 0x6a, 0x18, 0x1f, 0xfc,
	0xf8, 0xf2, 0x9f, 0x9f, 0x8b, 0x37, 0xd1, 0x0d, 0x3c, 0x7f, 0xf7, 0xa3, 0xdf, 0x35, 0x58, 0xc9,
	0xdc, 0x7f, 0x33, 0xee, 0xda, 0xe8, 0x93, 0xf9, 0x29, 0xcf, 0xdd, 0x7a, 0xd5, 0x4f, 0x2f, 0x0f,
	0x54, 0x9c, 0x3f, 0x16, 0x9c, 0x6f, 0x23, 0x13, 0x5f, 0xf4, 0x15, 0xc2, 0x4f, 0x99, 0xfd, 0x0c,
	0xfd, 0xa1, 0xc1, 0xda, 0x79, 0x03, 0x81, 0xee, 0xce, 0xa7, 0x92, 0xb3, 0x8a, 0xab, 0x9f, 0xff,
	0x5f, 0xb8, 0xaa, 0xe7, 0x33, 0x51, 0xcf, 0x1d, 0xd4, 0xb8, 0x70, 0x3d, 0x21, 0x7e, 0x2a, 0xf7,
	0xf8, 0x33, 0xf4, 0xab, 0x06, 0x2b, 0x5f, 0x3c, 0xa2, 0x83, 0xa3, 0x69, 0xab, 0xa3, 0xc6, 0x7c,
	0x42, 0x67, 0x66, 0xab, 0xfa, 0xd1, 0xe5, 0x40, 0x8a, 0xfb, 0x1d, 0xc1, 0x1d, 0xa3, 0xad, 0x59,
	0xdc, 0x6d, 0xea, 0x90, 0x98, 0xda, 0x64, 0x70, 0x34, 0x7d, 0x85, 0xc3, 0xe6, 0xfd, 0xe7, 0xc7,
	0x35, 0xed, 0xc5, 0x71, 0x4d, 0xfb, 0xfb, 0xb8, 0xa6, 0xfd, 0x74, 0x52, 0x2b, 0xbc, 0x38, 0xa9,
	0x15, 0xfe, 0x3c, 0xa9, 0x15, 0x1e, 0x6e, 0x0f, 0x59, 0xf4, 0x68, 0xd4, 0x4f, 0x26, 0x6f, 0x56,
	0xc8, 0x71, 0x03, 0x3f, 0x91, 0x9a, 0x24, 0x6f, 0x50, 0xd8, 0x2f, 0x8b, 0x47, 0xbd, 0xf1, 0x5f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x8b, 0x87, 0x2d, 0x3d, 0x65, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries a Demand Order by id.
	DemandOrderById(ctx context.Context, in *QueryGetDemandOrderRequest, opts ...grpc.CallOption) (*QueryGetDemandOrderResponse, error)
	// Queries a list of demand orders by status.
	DemandOrdersByStatus(ctx context.Context, in *QueryDemandOrdersByStatusRequest, opts ...grpc.CallOption) (*QueryDemandOrdersByStatusResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) DemandOrderById(ctx context.Context, in *QueryGetDemandOrderRequest, opts ...grpc.CallOption) (*QueryGetDemandOrderResponse, error) {
	out := new(QueryGetDemandOrderResponse)
	err := c.cc.Invoke(ctx, "/dymensionxyz.dymension.eibc.Query/DemandOrderById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DemandOrdersByStatus(ctx context.Context, in *QueryDemandOrdersByStatusRequest, opts ...grpc.CallOption) (*QueryDemandOrdersByStatusResponse, error) {
	out := new(QueryDemandOrdersByStatusResponse)
	err := c.cc.Invoke(ctx, "/dymensionxyz.dymension.eibc.Query/DemandOrdersByStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries a Demand Order by id.
	DemandOrderById(context.Context, *QueryGetDemandOrderRequest) (*QueryGetDemandOrderResponse, error)
	// Queries a list of demand orders by status.
	DemandOrdersByStatus(context.Context, *QueryDemandOrdersByStatusRequest) (*QueryDemandOrdersByStatusResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) DemandOrderById(ctx context.Context, req *QueryGetDemandOrderRequest) (*QueryGetDemandOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DemandOrderById not implemented")
}
func (*UnimplementedQueryServer) DemandOrdersByStatus(ctx context.Context, req *QueryDemandOrdersByStatusRequest) (*QueryDemandOrdersByStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DemandOrdersByStatus not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_DemandOrderById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetDemandOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DemandOrderById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dymensionxyz.dymension.eibc.Query/DemandOrderById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DemandOrderById(ctx, req.(*QueryGetDemandOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DemandOrdersByStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDemandOrdersByStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DemandOrdersByStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dymensionxyz.dymension.eibc.Query/DemandOrdersByStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DemandOrdersByStatus(ctx, req.(*QueryDemandOrdersByStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dymensionxyz.dymension.eibc.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DemandOrderById",
			Handler:    _Query_DemandOrderById_Handler,
		},
		{
			MethodName: "DemandOrdersByStatus",
			Handler:    _Query_DemandOrdersByStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dymensionxyz/dymension/eibc/query.proto",
}

func (m *QueryGetDemandOrderRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDemandOrderRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDemandOrderRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDemandOrdersByStatusRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDemandOrdersByStatusRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDemandOrdersByStatusRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x4a
	}
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Fulfiller) > 0 {
		i -= len(m.Fulfiller)
		copy(dAtA[i:], m.Fulfiller)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Fulfiller)))
		i--
		dAtA[i] = 0x32
	}
	if m.FulfillmentState != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.FulfillmentState))
		i--
		dAtA[i] = 0x28
	}
	if m.Limit != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Limit))
		i--
		dAtA[i] = 0x20
	}
	if len(m.RollappId) > 0 {
		i -= len(m.RollappId)
		copy(dAtA[i:], m.RollappId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.RollappId)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Type != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x10
	}
	if m.Status != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetDemandOrderResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDemandOrderResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDemandOrderResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DemandOrder != nil {
		{
			size, err := m.DemandOrder.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDemandOrdersByStatusResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDemandOrdersByStatusResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDemandOrdersByStatusResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.DemandOrders) > 0 {
		for iNdEx := len(m.DemandOrders) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DemandOrders[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}

func (m *QueryGetDemandOrderRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDemandOrdersByStatusRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Status != 0 {
		n += 1 + sovQuery(uint64(m.Status))
	}
	if m.Type != 0 {
		n += 1 + sovQuery(uint64(m.Type))
	}
	l = len(m.RollappId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Limit != 0 {
		n += 1 + sovQuery(uint64(m.Limit))
	}
	if m.FulfillmentState != 0 {
		n += 1 + sovQuery(uint64(m.FulfillmentState))
	}
	l = len(m.Fulfiller)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetDemandOrderResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DemandOrder != nil {
		l = m.DemandOrder.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDemandOrdersByStatusResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.DemandOrders) > 0 {
		for _, e := range m.DemandOrders {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}

func (m *QueryGetDemandOrderRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDemandOrderRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDemandOrderRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDemandOrdersByStatusRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDemandOrdersByStatusRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDemandOrdersByStatusRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= Status(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= RollappPacket_Type(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RollappId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RollappId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Limit", wireType)
			}
			m.Limit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Limit |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FulfillmentState", wireType)
			}
			m.FulfillmentState = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FulfillmentState |= FulfillmentState(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fulfiller", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Fulfiller = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDemandOrderResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDemandOrderResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDemandOrderResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DemandOrder", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DemandOrder == nil {
				m.DemandOrder = &DemandOrder{}
			}
			if err := m.DemandOrder.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDemandOrdersByStatusResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDemandOrdersByStatusResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDemandOrdersByStatusResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DemandOrders", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DemandOrders = append(m.DemandOrders, &DemandOrder{})
			if err := m.DemandOrders[len(m.DemandOrders)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
